version: '3.8'

services:
  rna-sequencing:
    image: lovehunter9/rna-sequencing:v0.0.1
    container_name: rna-sequencing
    user: "1000:1000"
    # runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./playbook:/home/rapids/notebooks/playbook
    ports:
      - 8888:8888
      - 8787:8787
      - 8786:8786
      - 8501:8501
      - 8050:8050
    shm_size: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    tty: true
    stdin_open: true