apiVersion: apps/v1
kind: Deployment
metadata:
  name: rna_sequencing
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: rna_sequencing
  annotations:
    applications.app.bytetrade.io/gpu-inject: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rna_sequencing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: rna_sequencing
    spec:
      containers:
        - name: rna_sequencing
          image: docker.io/beclab/lovehunter9-rna-sequencing:v0.0.3
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all" # 或者 "0", "1" 等，取决于你想用哪个 GPU
            - name: PARENT_DIR
              value: "/home/rapids/notebooks/playbook"
          readinessProbe:
            httpGet:
              path: /lab
              port: {{ .Values.port | default 3000 }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /lab
              port: {{ .Values.port | default 3000 }}
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            limits:
              cpu: 1900m
              memory: 19.5Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 1000m
              memory: 1.9Gi
              nvidia.com/gpu: 1
          securityContext:
            privileged: true
            capabilities:
              add: [ "SYS_ADMIN" ]
            runAsUser: 0
            runAsGroup: 0
          ports:
            - containerPort: 8888 # Jupyter Notebook
            - containerPort: 8787 # Dask Dashboard
            - containerPort: 8786 # Dask Scheduler
            - containerPort: 8501 # Streamlit
            - containerPort: 8050 # Plotly Dash
          volumeMounts:
            - name: rna_sequencing-data
              mountPath: /home/rapids/notebooks/playbook
              subPath: notebook
            - name: rna_sequencing-data
              mountPath: /dev/shm
              subPath: dshm
      restartPolicy: Always
      volumes:
        - name: rna_sequencing-data
          hostPath:
            type: DirectoryOrCreate
                {{- if .Values.sysVersion }}
                  {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: '{{ .Values.userspace.appCache }}'
                  {{- else }}
            path: '{{ .Values.userspace.appCache }}/rna_sequencing'
                  {{- end }}
                {{- else }}
            path: '{{ .Values.userspace.appCache }}/rna_sequencing'
                {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: rna_sequencing
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: rna_sequencing
spec:
  ports:
    - name: "{{ .Values.port | default 3000 }}"
      port: {{ .Values.port | default 3000 }}
      targetPort: {{ .Values.port | default 3000 }}
      protocol: TCP

    - name: dask-dashboard
      protocol: TCP
      port: 8787
      targetPort: 8787

    - name: dask-scheduler
      protocol: TCP
      port: 8786
      targetPort: 8786

    - name: streamlit
      protocol: TCP
      port: 8501
      targetPort: 8501

    - name: plotly-dash
      protocol: TCP
      port: 8050
      targetPort: 8050
  selector:
    io.kompose.service: rna_sequencing
status:
  loadBalancer: {}
