apiVersion: v1
kind: Secret
metadata:
  name: postgres-cron-secret
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: tensorzero
type: Opaque
stringData:
  POSTGRES_DB: "tensorzero"
  POSTGRES_USER: "{{ .Values.postgres.username }}" # "postgres"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}" # "postgres"

{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  name: postgres-cron-pvc*/}}
{{/*  namespace: {{ .Release.Namespace }}*/}}
{{/*  labels:*/}}
{{/*    io.kompose.service: tensorzero*/}}
{{/*spec:*/}}
{{/*  accessModes:*/}}
{{/*    - ReadWriteOnce*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: 1Gi*/}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorzero
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: tensorzero
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tensorzero
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: tensorzero
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: "docker.io/beclab/aboveos-busybox:1.37.0"
          command:
            - sh
            - '-c'
          args:
            - |
              mkdir -p /var/lib/clickhouse
              chown -R 1000:1000 /var/lib/clickhouse
              chmod -R 755 /var/lib/clickhouse
              mkdir -p /var/lib/postgresql/data
              chown -R 999:999 /var/lib/postgresql/data
              chmod -R 755 /var/lib/postgresql/data
              mkdir -p /var/run/postgresql
              chown -R 999:999 /var/run/postgresql
              chmod -R 755 /var/run/postgresql
          resources: { }
          volumeMounts:
            - name: tensorzero-data
              mountPath: /var/lib/clickhouse
              subPath: clickhouse
            - name: tensorzero-data
              mountPath: /var/lib/postgresql/data
              subPath: pg-data
            - name: tensorzero-data
              mountPath: /var/run/postgresql
              subPath: pg-run
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
      containers:
        - name: clickhouse
          image: "docker.io/beclab/clickhouse-clickhouse-server:25.5"
          env:
            - name: CLICKHOUSE_USER
              value: "chuser"
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
            - name: CLICKHOUSE_PASSWORD
              value: "chpassword"
          ports:
            - containerPort: 8123
              name: ch-http
            - containerPort: 9000
              name: ch-native
          volumeMounts:
            - name: tensorzero-data
              mountPath: /var/lib/clickhouse
              subPath: clickhouse
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "wget --spider --tries 1 http://chuser:chpassword@localhost:8123/ping"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "wget --spider --tries 1 http://chuser:chpassword@localhost:8123/ping"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1

        - name: gateway
          image: tensorzero/gateway:2026.2.2
          command: [ "gateway" ]
          args: [ "--default-config", "--run-postgres-migrations" ]
          env:
            - name: TENSORZERO_CLICKHOUSE_URL
              value: "http://chuser:chpassword@localhost:8123/tensorzero"
            - name: TENSORZERO_POSTGRES_URL
              value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@localhost:{{ .Values.postgres.port }}/tensorzero?sslmode=disable"
{{/*              value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.tensorzerodb }}?sslmode=disable"*/}}
          ports:
            - containerPort: 3000
              name: gateway
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1

        - name: ui
          image: tensorzero/ui:2026.2.2
          env:
            - name: TENSORZERO_POSTGRES_URL
              value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@localhost:{{ .Values.postgres.port }}/tensorzero?sslmode=disable"
{{/*              value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.databases.tensorzerodb }}?sslmode=disable"*/}}
            - name: TENSORZERO_GATEWAY_URL
              value: "http://localhost:3000"
          ports:
            - containerPort: 4000
              name: ui
          livenessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1

        - name: postgres
          image: lovehunter9/postgres-14-cron:v0.0.2
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          ports:
            - containerPort: 5432
              name: psql
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-cron-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-cron-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-cron-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: tensorzero-data
              mountPath: /var/lib/postgresql/data
              subPath: pg-data
            - name: tensorzero-data
              mountPath: /var/run/postgresql
              subPath: pg-run
{{/*            - name: postgres-storage*/}}
{{/*              mountPath: /var/lib/postgresql/data*/}}
          readinessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            exec:
              command: [ "pg_isready", "-U", "postgres" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1

      restartPolicy: Always
      volumes:
        - name: tensorzero-data
          hostPath:
            type: DirectoryOrCreate
                {{- if .Values.sysVersion }}
                  {{- if semverCompare ">=1.12.3-0" (toString .Values.sysVersion) }}
            path: '{{ .Values.userspace.appCache }}'
                  {{- else }}
            path: '{{ .Values.userspace.appCache }}/tensorzero'
                  {{- end }}
                {{- else }}
            path: '{{ .Values.userspace.appCache }}/tensorzero'
                {{- end }}
{{/*        - name: postgres-storage*/}}
{{/*          persistentVolumeClaim:*/}}
{{/*            claimName: postgres-cron-pvc*/}}

---
apiVersion: v1
kind: Service
metadata:
  name: tensorzero
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: tensorzero
spec:
  ports:
    - name: ch-http
      port: 8123
      targetPort: 8123
    - name: ch-native
      port: 9000
      targetPort: 9000
    - name: gateway
      port: 3000
      targetPort: 3000
    - name: ui
      port: 4000
      targetPort: 4000
    - name: psql
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: tensorzero
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sharedentrances-tensorzero
  namespace: {{ .Release.Namespace }}
  labels:
    io.kompose.service: tensorzero
spec:
  ports:
    - name: "4000"
      port: 80
      targetPort: 4000
  selector:
    io.kompose.service: tensorzero
status:
  loadBalancer: {}
